services:
  website_vijaykumardvk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website_vijaykumardvk
    restart: unless-stopped
    working_dir: /var/www/vijaykumardvk
    expose:
      - "9000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network

volumes:
  vijaykumardvk:
    name: vijaykumardvk