pipeline {
  agent {
    docker {
      image 'docker:27-cli'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {

    stage('Load env file') {
      steps {
        withCredentials([
          file(credentialsId: 'vijaykumardvk-prod-env', variable: 'ENV_FILE')
        ]) {
          sh 'cp $ENV_FILE backend/.env.production'
        }
      }
    }

    stage('Build Image') {
      steps {
        dir('backend') {
          sh 'docker build -t website_vijaykumardvk:latest .'
        }
      }
    }

    stage('Run Containers') {
      steps {
        dir('backend') {
          sh 'docker compose up -d'
        }
      }
    }
  }
}
