pipeline {
  agent {
    docker {
      image 'docker:27-cli'
      args '-v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {
    stage('Stop & Clean Old Containers') {
      steps {
        dir('backend') {
          sh 'docker compose down --remove-orphans || true'
        }
      }
    }

    stage('Remove Old Image (Optional)') {
      steps {
        sh '''
        docker images | grep website_vijaykumardvk && \
        docker rmi -f website_vijaykumardvk || true
        '''
      }
    }

    stage('Load env file') {
      steps {
        withCredentials([
          file(credentialsId: 'vijaykumardvk-prod-env', variable: 'ENV_FILE')
        ]) {
          sh '''
            cp $ENV_FILE .env.production
            cp .env.production .env
          '''
        }
      }
    }

    stage('Build Image') {
      steps {
        dir('backend') {
          sh 'docker build -t website_vijaykumardvk:latest .'
        }
      }
    }

    stage('Run Containers') {
      steps {
        dir('backend') {
          sh 'docker compose up -d --build'
        }
      }
    }

    stage('Post Deploy – Laravel Setup') {
      steps {
        sh '''
        docker exec vijaykumardvk_app sh -c "
          composer update
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        "
        '''
      }
    }
  }
}
